<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://manascape.org"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
		   xmlns:jaxb="http://java.sun.com/xml/ns/jaxb" 
		   targetNamespace="http://manascape.org">
	
	
	<!-- 
	Login Sessions
	-->
	
	<xs:complexType name="UserSessionDTO">
		<xs:sequence>
			<xs:element name="id"				type="xs:long"		minOccurs="1" maxOccurs="1" />
			<xs:element name="username"			type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="displayName"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="staff"	 		type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="fmod"		 		type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="pmod"		 		type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="currentIP"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="supportDisabled"	type="xs:boolean" 	minOccurs="1" maxOccurs="1" />
			
			<xs:element name="sessionId"		type="xs:long"		minOccurs="1" maxOccurs="1" />
			<xs:element name="sessionHash"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="secure"	 		type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="mod"				type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="dest"				type="xs:string"	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="SessionCheckDTO">
		<xs:sequence>
			<xs:element name="sessionId"	type="xs:long"		minOccurs="1" maxOccurs="1" />
			<xs:element name="secure"	 	type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="endDate"		type="xs:string"	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	
	<!-- 
	Account Management
	-->
			   
	<xs:complexType name="PasswordRequestDTO">
		<xs:sequence>
			<xs:element name="userId"		type="xs:long"		minOccurs="1" maxOccurs="1" />
			<xs:element name="passwordHash"	type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="passwordSalt"	type="xs:string"	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	
	<!--
	News Articles
	-->
	
	<xs:complexType name="NewsFeedDTO">
		<xs:sequence>
			<xs:element name="id"			type="xs:int"		minOccurs="1" maxOccurs="1" />
			<xs:element name="title"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="date"			type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="description"	type="xs:string"	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="NewsItemDTO">
		<xs:sequence>
			<xs:element name="id"			type="xs:int"		minOccurs="1" maxOccurs="1" />
			<xs:element name="title"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="date"			type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="category"		type="xs:int"		minOccurs="1" maxOccurs="1" />
			<xs:element name="description"	type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="body"			type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="lastEditor"	type="xs:string" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="lastEditDate"	type="xs:string" 	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="NewsArchiveDTO">
		<xs:sequence>
			<xs:element name="id"		type="xs:int"		minOccurs="1" maxOccurs="1" />
			<xs:element name="title"	type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="date"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="category"	type="xs:int"		minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="NewsFieldDTO">
		<xs:sequence>
			<xs:element name="title"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="category"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="description"	type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="body"			type="xs:string"	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="NewsErrorDTO">
		<xs:sequence>
			<xs:element name="title"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="category"		type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="description"	type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="body"			type="xs:string"	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	
	<!--
	Staff Center Users
	-->
	
	<xs:complexType name="UserListUserDTO">
		<xs:sequence>
			<xs:element name="id"				type="xs:long"		minOccurs="1" maxOccurs="1" />
			<xs:element name="username"			type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="displayName"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="creationDate"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="creationIP"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="currentIP"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="staff"			type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="fmod"				type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="pmod"				type="xs:boolean"	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="UserListDTO">
		<xs:sequence>
			<xs:element name="currentPage"		type="xs:int"			minOccurs="1" maxOccurs="1" />
			<xs:element name="pageCount"		type="xs:int"			minOccurs="1" maxOccurs="1" />
			<xs:element name="usernameSearch"	type="xs:string"		minOccurs="1" maxOccurs="1" />
			<xs:element name="ipSearch"			type="xs:string"		minOccurs="1" maxOccurs="1" />
			<xs:element name="userList"			type="UserListUserDTO"	minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="UserDetailsDTO">
		<xs:sequence>
			<xs:element name="id"				type="xs:long"		minOccurs="1" maxOccurs="1" />
			<xs:element name="username"			type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="displayName"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="dob"				type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="country"			type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="creationDate"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="creationIP"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="currentIP"		type="xs:string"	minOccurs="1" maxOccurs="1" />
			<xs:element name="staff"	 		type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="fmod"		 		type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="pmod"		 		type="xs:boolean"	minOccurs="1" maxOccurs="1" />
			<xs:element name="supportDisabled"	type="xs:boolean" 	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="LoginAttemptInfoDTO">
		<xs:sequence>
			<xs:element name="pageInfo"	type="PageInfoDTO"			minOccurs="1" maxOccurs="1" />
			<xs:element name="entries"	type="LoginAttemptEntryDTO"	minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="LoginAttemptEntryDTO">
		<xs:sequence>
			<xs:element name="ip"			type="xs:string" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="date"			type="xs:string" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="successful"	type="xs:boolean" 	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="LoginSessionInfoDTO">
		<xs:sequence>
			<xs:element name="pageInfo"	type="PageInfoDTO"			minOccurs="1" maxOccurs="1" />
			<xs:element name="entries"	type="LoginSessionEntryDTO"	minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="LoginSessionEntryDTO">
		<xs:sequence>
			<xs:element name="ip"			type="xs:string" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="startDate"	type="xs:string" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="endDate"		type="xs:string" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="secure"		type="xs:boolean" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="startMod"		type="xs:string" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="currentMod"	type="xs:string" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="startDest"	type="xs:string" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="currentDest"	type="xs:string" 	minOccurs="1" maxOccurs="1" />
			<xs:element name="active"		type="xs:boolean"	minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
	
	<!--
	Misc.
	-->
	
	<xs:complexType name="PageInfoDTO">
		<xs:sequence>
			<xs:element name="currentPage"		type="xs:int"				minOccurs="1" maxOccurs="1" />
			<xs:element name="pageCount"		type="xs:int"				minOccurs="1" maxOccurs="1" />
			<xs:element name="fullEntryCount"	type="xs:long"				minOccurs="1" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>